import { lazy } from "react"
import {
  ArrowLeftRight,
  Braces,
  Clock,
  Code2,
  Database,
  Diff,
  FileCode,
  FileCode2,
  FileText,
  Fingerprint,
  Globe,
  Hash,
  KeyRound,
  Lock,
  Network,
  Search,
  Shield,
  Tag,
  Timer,
  Type,
} from "lucide-react"
import type { RegistryEntry } from "./types"

export const tools: RegistryEntry[] = [
  // ── Text & Comparison ─────────────────────────────────────────────────────
  {
    id: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts side-by-side with color highlights",
    category: "Text & Comparison",
    icon: Diff,
    component: lazy(() => import("../tools/diff-checker/DiffChecker")),
  },
  {
    id: "json-escaper",
    name: "JSON Escaper",
    description: "Escape and unescape JSON string values",
    category: "Text & Comparison",
    icon: Braces,
    component: lazy(() => import("../tools/json-escaper/JsonEscaper")),
  },
  {
    id: "text-inspector",
    name: "Case Converter",
    description: "Convert case and inspect text statistics",
    category: "Text & Comparison",
    icon: Type,
    component: lazy(() => import("../tools/text-inspector/TextInspector")),
  },

  // ── Encoding & Formatting ─────────────────────────────────────────────────
  {
    id: "codec",
    name: "Base64 & URL Codec",
    description: "Encode and decode Base64 and URL strings",
    category: "Encoding & Formatting",
    icon: ArrowLeftRight,
    component: lazy(() => import("../tools/codec/Codec")),
  },
  {
    id: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities",
    category: "Encoding & Formatting",
    icon: Tag,
    component: lazy(() => import("../tools/html-entities/HtmlEntities")),
  },
  {
    id: "html-xml-formatter",
    name: "HTML / XML Formatter",
    description: "Beautify or minify HTML and XML markup",
    category: "Encoding & Formatting",
    icon: FileCode2,
    component: lazy(() => import("../tools/html-xml-formatter/HtmlXmlFormatter")),
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    category: "Encoding & Formatting",
    icon: Code2,
    component: lazy(() => import("../tools/json-formatter/JsonFormatter")),
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify and format SQL queries",
    category: "Encoding & Formatting",
    icon: Database,
    component: lazy(() => import("../tools/sql-formatter/SqlFormatter")),
  },
  {
    id: "yaml-json",
    name: "YAML ⇄ JSON",
    description: "Convert between YAML and JSON instantly",
    category: "Encoding & Formatting",
    icon: FileCode,
    component: lazy(() => import("../tools/yaml-json/YamlJson")),
  },

  // ── Cryptography & Security ───────────────────────────────────────────────
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "Cryptography & Security",
    icon: Hash,
    component: lazy(() => import("../tools/hash-generator/HashGenerator")),
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    description: "Decode and inspect JSON Web Tokens",
    category: "Cryptography & Security",
    icon: Shield,
    component: lazy(() => import("../tools/jwt-debugger/JwtDebugger")),
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "Cryptography & Security",
    icon: Lock,
    component: lazy(() => import("../tools/password-generator/PasswordGenerator")),
  },
  {
    id: "rsa-generator",
    name: "RSA Key Generator",
    description: "Generate RSA key pairs in PEM format",
    category: "Cryptography & Security",
    icon: KeyRound,
    component: lazy(() => import("../tools/rsa-generator/RsaGenerator")),
  },

  // ── Development Tools ─────────────────────────────────────────────────────
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Translate cron expressions to plain English",
    category: "Development Tools",
    icon: Clock,
    component: lazy(() => import("../tools/cron-parser/CronParser")),
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live markdown editor with rendered preview",
    category: "Development Tools",
    icon: FileText,
    component: lazy(() => import("../tools/markdown-preview/MarkdownPreview")),
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test patterns with real-time match highlighting",
    category: "Development Tools",
    icon: Search,
    component: lazy(() => import("../tools/regex-tester/RegexTester")),
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Bulk generate Version 4 UUIDs / GUIDs",
    category: "Development Tools",
    icon: Fingerprint,
    component: lazy(() => import("../tools/uuid-generator/UuidGenerator")),
  },

  // ── Network & DevOps ──────────────────────────────────────────────────────
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Complete reference for all HTTP status codes",
    category: "Network & DevOps",
    icon: Globe,
    component: lazy(() => import("../tools/http-status-codes/HttpStatusCodes")),
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate IPv4 network addresses and host ranges",
    category: "Network & DevOps",
    icon: Network,
    component: lazy(() => import("../tools/subnet-calculator/SubnetCalculator")),
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to dates and back",
    category: "Network & DevOps",
    icon: Timer,
    component: lazy(() => import("../tools/timestamp-converter/TimestampConverter")),
  },
]
